jekyll.environment: production
site.github.pages_env: dotcom
site.url: https://alejosazon.github.io
site.baseurl: /elsazondealejo
site.github.url: https://alejosazon.github.io/elsazondealejo
name: eN PiTALiTO
author: Julian Franco
timezone: America/Bogota

email: info@enpitalito.com
twitter: https://twitter.com/enpitalito/
facebook: https://facebook.com/enpitalito/
instagram: https://instagram.com/enpitalito/
telefono:

permalink: /:categories/:title/